name: Build Wheel

# run on new version tag
on:
    push:
    workflow_dispatch:
        
jobs:
    job:
        name: Build wheel
        runs-on: ubuntu-latest
        steps:
            - name: Prepare python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install python dependencies
              run: pip install build
              
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Build wheel
              run: python -m build 
